server:
  port: 9090
  servlet:
    session:
      timeout: 86400s
      cookie:
        http-only: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/honey2024?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: pjk520
    initialization-mode: always
    schema: classpath:db/schema.sql
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

file: 
  upload-path: springboot/src/main/resources/static/uploads/
  access-path: /uploads/